export const UPDATE_COMMENTS = "UPDATE_COMMENTS";
export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
export const LIKE_COMMENT = "LIKE_COMMENT";
export const REMOVE_LIKE_COMMENT = "REMOVE_LIKE_COMMENT";
